"""foreign keys and models are fixed

Revision ID: 167e21f6e3c2
Revises:
Create Date: 2026-04-17 18:01:49.226314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "167e21f6e3c2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    with op.batch_alter_table("auth_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_user_id"), ["id"], unique=False)

    op.create_table(
        "blog_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_category_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_blog_category_slug"), ["slug"], unique=True
        )

    op.create_table(
        "blog_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_location", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_location_id"), ["id"], unique=False)

    op.create_table(
        "blog_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("pub_date", sa.DateTime(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["blog_category.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["blog_location.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_post", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_post_id"), ["id"], unique=False)

    op.create_table(
        "blog_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["blog_post.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blog_comment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blog_comment_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_comment_id"))

    op.drop_table("blog_comment")
    with op.batch_alter_table("blog_post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_post_id"))

    op.drop_table("blog_post")
    with op.batch_alter_table("blog_location", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_location_id"))

    op.drop_table("blog_location")
    with op.batch_alter_table("blog_category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blog_category_slug"))
        batch_op.drop_index(batch_op.f("ix_blog_category_id"))

    op.drop_table("blog_category")
    with op.batch_alter_table("auth_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_user_id"))

    op.drop_table("auth_user")
    # ### end Alembic commands ###
