"""add author_id to categories and locations

Revision ID: 055a6989ad7b
Revises: 7c1eb8ee7b52
Create Date: 2026-05-27 22:28:05.652421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "055a6989ad7b"
down_revision: Union[str, Sequence[str], None] = "7c1eb8ee7b52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_category", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "blog_category", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("blog_location", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "blog_location", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "blog_location", type_="foreignkey")
    op.drop_column("blog_location", "author_id")
    op.drop_constraint(None, "blog_category", type_="foreignkey")
    op.drop_column("blog_category", "author_id")
    # ### end Alembic commands ###
