"""add post images

Revision ID: 68265aa46b95
Revises: e3556c3ba691
Create Date: 2026-05-27 21:23:51.982153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68265aa46b95"
down_revision: Union[str, Sequence[str], None] = "e3556c3ba691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_post_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["blog_post.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blog_post_image_id"), "blog_post_image", ["id"], unique=False
    )
    op.drop_column("blog_post", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_post",
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_blog_post_image_id"), table_name="blog_post_image")
    op.drop_table("blog_post_image")
    # ### end Alembic commands ###
