"""add author_id to categories and locations

Revision ID: 7c1eb8ee7b52
Revises: 68265aa46b95
Create Date: 2026-05-27 22:24:09.938164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c1eb8ee7b52"
down_revision: Union[str, Sequence[str], None] = "68265aa46b95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_image_id"), table_name="comment_image")
    op.drop_table("comment_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_image",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["blog_comment.id"],
            name=op.f("comment_image_comment_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comment_image_pkey")),
    )
    op.create_index(op.f("ix_comment_image_id"), "comment_image", ["id"], unique=False)
    # ### end Alembic commands ###
