"""make category description nullable

Revision ID: e67c037fd66f
Revises: 3982b1ab1112
Create Date: 2026-05-27 23:20:32.721355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e67c037fd66f"
down_revision: Union[str, Sequence[str], None] = "3982b1ab1112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["blog_comment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_image_id"), "comment_image", ["id"], unique=False)
    op.alter_column(
        "blog_category", "title", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column(
        "blog_category", "description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("blog_category", "slug", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "blog_category", "is_published", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "blog_category",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_comment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_comment", "is_published", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "blog_location", "name", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column(
        "blog_location", "is_published", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "blog_location",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_post", "title", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column("blog_post", "text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "blog_post",
        "pub_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "blog_post", "is_published", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "blog_post",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "blog_post",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_post", "is_published", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "blog_post",
        "pub_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("blog_post", "text", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "blog_post", "title", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.alter_column(
        "blog_location",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_location", "is_published", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "blog_location", "name", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.alter_column(
        "blog_comment", "is_published", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "blog_comment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_category",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "blog_category", "is_published", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("blog_category", "slug", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "blog_category", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "blog_category", "title", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.drop_index(op.f("ix_comment_image_id"), table_name="comment_image")
    op.drop_table("comment_image")
    # ### end Alembic commands ###
